### ISSUE TITLE
Can't create index

### ISSUE THREAD

**Issue by epwalsh** [kkharji/sqlite.lua#143]
Hey @kkharji,

I'm struggling to create an index. This is what I'm running:

```lua
local sqlite = require("sqlite.db")

local db = sqlite {
  uri = "/tmp/db",
  notes = {
    id = { "text", required = true, unique = true, primary = true },
    alias = { "text", required = true },
  },
}
db:eval("CREATE INDEX IF NOT EXISTS alias_idx ON notes (alias)")
```

By I get this error:

```
Error detected while processing command line:
E5113: Error while calling lua chunk: ...vanw/.config/nvim/plugged/sqlite.lua/lua/sqlite/stmt.lua:35: sqlite.lua: sql statement parse, , stmt: `CREATE INDEX IF NOT EXISTS alias_idx ON notes (alias)`, err: `(`bad parameter o
r other API misuse`)`
stack traceback:
        [C]: in function 'assert'
        ...vanw/.config/nvim/plugged/sqlite.lua/lua/sqlite/stmt.lua:35: in function 'parse'
        .../evanw/.config/nvim/plugged/sqlite.lua/lua/sqlite/db.lua:287: in function 'eval'
        test/db.lua:10: in main chunk
```

Any idea?

**Comment by kkharji** [comment]
> Hey @kkharji,
> 
> 
> 
> I'm struggling to create an index. This is what I'm running:
> 
> 
> 
> ```lua
> 
> local sqlite = require("sqlite.db")
> 
> 
> 
> local db = sqlite {
> 
>   uri = "/tmp/db",
> 
>   notes = {
> 
>     id = { "text", required = true, unique = true, primary = true },
> 
>     alias = { "text", required = true },
> 
>   },
> 
> }
> 
> db:eval("CREATE INDEX IF NOT EXISTS alias_idx ON notes (alias)")
> 
> ```
> 
> 
> 
> By I get this error:
> 
> 
> 
> ```
> 
> Error detected while processing command line:
> 
> E5113: Error while calling lua chunk: ...vanw/.config/nvim/plugged/sqlite.lua/lua/sqlite/stmt.lua:35: sqlite.lua: sql statement parse, , stmt: `CREATE INDEX IF NOT EXISTS alias_idx ON notes (alias)`, err: `(`bad parameter o
> 
> r other API misuse`)`
> 
> stack traceback:
> 
>         [C]: in function 'assert'
> 
>         ...vanw/.config/nvim/plugged/sqlite.lua/lua/sqlite/stmt.lua:35: in function 'parse'
> 
>         .../evanw/.config/nvim/plugged/sqlite.lua/lua/sqlite/db.lua:287: in function 'eval'
> 
>         test/db.lua:10: in main chunk
> 
> ```
> 
> 
> 
> Any idea?

🤔 most likely because the db need to be manually opened.

The reason this happens is because sqlite constructor is super lazy and doesn't do anything until the first operations. 

try 
```lua
db:with_open(function()
    return db:eval("...")
end)
```

or else try insert a note to notes table before evaluating

**Comment by epwalsh** [comment]
Ah, that worked! Thanks :)
