### ISSUE TITLE
SQLite and Installation Questions

### ISSUE THREAD

**Issue by CharlesARoy** [kkharji/sqlite.lua#145]
I'm trying to install sqlite.lua to enable persistent history in [nvim-neoclip.lua](https://github.com/AckslD/nvim-neoclip.lua) but I'm having a hard time getting going.

I'm working on a machine running Ubuntu 20.04.4 LTS. From the Installation instructions, I should install sqlite3 and libsqlite3-dev with a command like: `sudo apt-get install sqlite3 libsqlite3-dev`; however, unfortunately, I don't have sudo privileges on this machine. 

I was able to install sqlite3 with Anaconda (and by [compiling it from source](https://www.sqlite.org/howtocompile.html)) but I can't find a way to install libsqlite3-dev in a similar fashion.

Without libsqlite3-dev installed, when I enable persistent history in Neoclip, it doesn't seem to work. When I enable continuous sync in Neoclip, I get errors like this:
![image](https://user-images.githubusercontent.com/46253001/188992640-e7a970ed-20d2-4bc4-90cc-51c8f155cede.png)

Given this, should I conclude that libsqlite3-dev is in fact necessary to get sqlite.lua working in Linux? If yes, do you have any suggestions on how to install it without root?

**Comment by kkharji** [comment]
> Given this, should I conclude that libsqlite3-dev is in fact necessary to get sqlite.lua working in Linux? 

Hmmm I'm not quite sure. You just findout where libsqlite3.so is stored in your filesystem and just set `vim.g.sqlite_clib_path` to it.

If installed globally, as with github actions there isn't a need to setup sqlite_clib_path variable.

Try that and let me know

**Comment by CharlesARoy** [comment]
Ultimately I got permission to install sqlite3 and libsqlite3-dev system-wide with sudo, and everything works perfectly now.

For anyone else with a similar issue, I couldn't find a way to install libsqlite3-dev from source. However, I did find [this thread](https://forum.lazarus.freepascal.org/index.php?topic=26038.0) that potentially indicates a solution if you install sqlite3 from source:

> Just some info about this problem:
> libsqlite3-0 package installing libsqlite3.so.0.8.6 file and makes link to it named libsqlite3.so.0
> That's the reason of missing libsqlite3.so
> libsqlite3-dev makes link to libsqlite3.so.0.8.6 named libsqlite3.so

See also:
https://packages.ubuntu.com/focal/sqlite3
https://packages.ubuntu.com/focal/libsqlite3-dev
