### ISSUE TITLE
Remove screenshot from repo

### ISSUE THREAD

**Issue by clason** [kkharji/sqlite.lua#153]
As this repository is meant to (among other things) being cloned as a Neovim plugin, having the 1Mb screenshot under version control is wasteful.

Instead, it is better practice to upload the screenshot to Github's user content server (by dragging it into the rich text editor when editing the README); then it can be removed from the repo.

If that is acceptable, I can make a PR for that.

**Comment by kkharji** [comment]
Hey @clason, It would be great. I'm unaware of github user content server

**Comment by clason** [comment]
done!
