### ISSUE TITLE
Add libsqlite3.so.0 to `linux_paths` variable.

### ISSUE THREAD

**Issue by Weissle** [kkharji/sqlite.lua#166]
https://github.com/kkharji/sqlite.lua/blob/376e4735c48e07dade3e6ff5f09a654a04f5d4ba/lua/sqlite/defs.lua#L37
In my WSL2 Ubuntu, the `libsqlite3.so` cannot be found because it's name is `libsqlite3.so.0`, Could you add this `/usr/lib/x86_64-linux-gnu/libsqlite3.so.0` ??

```
[13:21:45] (base) ~/.config/dotfiles $ cd /usr/lib/x86_64-linux-gnu
[13:26:23] (base) /usr/lib/x86_64-linux-gnu $ ll libsq*
lrwxrwxrwx   19 root  4 Nov  2022 libsqlite3.so.0 -> libsqlite3.so.0.8.6
.rw-r--r-- 1.2M root  4 Nov  2022 libsqlite3.so.0.8.6

```

**Comment by kkharji** [comment]
Sure you can go ahead and open PR to this new path. Thanks.
