### ISSUE TITLE
Search `$PATH` for `sqlite3` or use `which sqlite3`

### ISSUE THREAD

**Issue by mrjones2014** [kkharji/sqlite.lua#168]
I'm on macOS and have sqlite installed via Nix package manager. Instead of searching a static list of paths, it should support alternative setups by searching `$PATH` or using `which sqlite3`.

**Comment by kkharji** [comment]
I use nix as well. I just set `LIBSQLITE` variable that will be checked by sqlite.lua. `which sqlite3` seems like a good idea as a last option after searching the paths

LIBSQLITE = "${pkgs.sqlite.out}/lib/libsqlite3.dylib"

**Comment by mrjones2014** [comment]
Gotcha, I wasn't aware of the `LIBSQLITE` variable.

I can throw up a PR for this tomorrow.

**Comment by mrjones2014** [comment]
Closing as it looks like it's not really possible to do this.
